services:
  db:
    image: postgres:16-alpine
    env_file: .env
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    networks:
      - ms-net

  auth:
    build: ./auth
    container_name: auth
    ports:
      - "3500:3500"
    env_file: .env
    depends_on:
      - db
    networks:
      - ms-net

  profiles:
    build: ./profiles
    container_name: profiles
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - auth
    networks:
      - ms-net

  sms:
    build: ./sms
    container_name: sms
    ports:
      - "6379:6379"
    env_file: .env
    networks:
      - ms-net

volumes:
  dbdata:

networks:
  ms-net:
    driver: bridge
